### PR TITLE
feature: create a miraclemsg subproject

### PR DESCRIPTION
**Pull request by mattkae**
## What's new?
- Created the `miraclemsg` subproject, which is mostly a copy of `swaymsg`
- Cleaned up the files using clang-tidy
- Updated CI and the snap to include it

### CODE REVIEW

**Review by Conan-Kudo — CHANGES_REQUESTED** [review]
Missing license headers.

**Comment by mattkae** [comment]
> Missing license headers.

Fixed

**Comment by Conan-Kudo** [comment]
> > Missing license headers.
> 
> Fixed

For the parts from `swaymsg`, you should probably also add to the license headers something like:

```
 Portions of this code originate from swaymsg, licensed under the MIT license.
 See the LICENSE.Sway file for details.
```

And you'll need to add `LICENSE.Sway` with a copy of the license file from Sway into the miraclemsg folder.

**Comment by mattkae** [comment]
[Implement miraclemsg](https://trello.com/c/TlwhNKLO/6-implement-miraclemsg)

**Comment by mattkae** [comment]
@Conan-Kudo you can check this out again :angel:

**Review by Conan-Kudo — APPROVED** [review]

**Pull request merged**
